CREATE TABLE utenti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(200) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    ruolo VARCHAR(20) NOT NULL DEFAULT 'USER'
        CHECK (ruolo IN ('USER', 'ADMIN')),
    attivo BOOLEAN NOT NULL DEFAULT TRUE,
    data_creazione TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE portafogli (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_id BIGINT NOT NULL UNIQUE REFERENCES utenti(id),
    saldo_totale NUMERIC(12,2) NOT NULL DEFAULT 0,
    saldo_riservato NUMERIC(12,2) NOT NULL DEFAULT 0,
    versione BIGINT NOT NULL DEFAULT 0,
    data_modifica TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (saldo_totale >= 0),
    CHECK (saldo_riservato >= 0),
    CHECK (saldo_riservato <= saldo_totale)
);

CREATE TABLE categorie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(100) NOT NULL UNIQUE,
    attiva BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE prodotti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id BIGINT NOT NULL REFERENCES categorie(id),
    sku VARCHAR(30) NOT NULL UNIQUE,
    nome VARCHAR(200) NOT NULL,
    descrizione TEXT,
    prezzo_fisso NUMERIC(12,2),
    astabile BOOLEAN NOT NULL DEFAULT FALSE,
    quantita_disponibile INT NOT NULL DEFAULT 0,
    quantita_bloccata INT NOT NULL DEFAULT 0,
    attivo BOOLEAN NOT NULL DEFAULT TRUE,
    versione BIGINT NOT NULL DEFAULT 0,
    data_creazione TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (prezzo_fisso IS NULL OR prezzo_fisso > 0),
    CHECK (quantita_disponibile >= 0),
    CHECK (quantita_bloccata >= 0)
);

CREATE TABLE inventario_utenti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_id BIGINT NOT NULL REFERENCES utenti(id),
    prodotto_id BIGINT NOT NULL REFERENCES prodotti(id),
    quantita INT NOT NULL DEFAULT 0 CHECK (quantita >= 0),
    versione BIGINT NOT NULL DEFAULT 0,
    UNIQUE (utente_id, prodotto_id)
);

CREATE TABLE aste (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prodotto_id BIGINT NOT NULL REFERENCES prodotti(id),
    admin_id BIGINT NOT NULL REFERENCES utenti(id),
    vincitore_id BIGINT REFERENCES utenti(id),
    stato VARCHAR(20) NOT NULL DEFAULT 'PROGRAMMATA'
        CHECK (stato IN (
            'PROGRAMMATA', 'STANZA_APERTA', 'APERTA', 'CHIUSA', 'ANNULLATA'
        )),
    prezzo_iniziale NUMERIC(12,2) NOT NULL CHECK (prezzo_iniziale > 0),
    incremento_minimo NUMERIC(12,2) NOT NULL DEFAULT 1.00
        CHECK (incremento_minimo > 0),
    offerta_corrente NUMERIC(12,2),
    inizio_at TIMESTAMPTZ NOT NULL,
    fine_at TIMESTAMPTZ NOT NULL,
    chiusa_at TIMESTAMPTZ,
    sequence BIGINT NOT NULL DEFAULT 0,
    versione BIGINT NOT NULL DEFAULT 0,
    data_creazione TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (fine_at >= inizio_at + INTERVAL '7 minutes')
);

CREATE TABLE offerte (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asta_id BIGINT NOT NULL REFERENCES aste(id),
    offerente_id BIGINT NOT NULL REFERENCES utenti(id),
    client_bid_id UUID NOT NULL UNIQUE,
    importo NUMERIC(12,2) NOT NULL CHECK (importo > 0),
    data_offerta TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE movimenti_portafoglio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portafoglio_id BIGINT NOT NULL REFERENCES portafogli(id),
    asta_id BIGINT REFERENCES aste(id),
    tipo VARCHAR(30) NOT NULL CHECK (tipo IN (
        'IMPOSTAZIONE_SALDO', 'RISERVA_OFFERTA', 'RILASCIO_OFFERTA',
        'PAGAMENTO_ASTA', 'INCASSO_ASTA', 'ACQUISTO_FISSO'
    )),
    importo NUMERIC(12,2) NOT NULL CHECK (importo > 0),
    saldo_totale_dopo NUMERIC(12,2) NOT NULL,
    saldo_riservato_dopo NUMERIC(12,2) NOT NULL,
    data_movimento TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_aste_stato_inizio ON aste(stato, inizio_at);
CREATE INDEX idx_aste_stato_fine ON aste(stato, fine_at);
CREATE INDEX idx_aste_prodotto ON aste(prodotto_id);
CREATE INDEX idx_aste_vincitore ON aste(vincitore_id, chiusa_at DESC);
CREATE INDEX idx_offerte_asta_data ON offerte(asta_id, data_offerta DESC);
CREATE INDEX idx_movimenti_wallet_data
    ON movimenti_portafoglio(portafoglio_id, data_movimento DESC);
