CREATE TABLE portafogli (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_id BIGINT NOT NULL UNIQUE REFERENCES utenti(id),
    saldo_totale NUMERIC(12,2) NOT NULL DEFAULT 0,
    saldo_riservato NUMERIC(12,2) NOT NULL DEFAULT 0,
    versione BIGINT NOT NULL DEFAULT 0,
    data_modifica TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (saldo_totale >= 0),
    CHECK (saldo_riservato >= 0),
    CHECK (saldo_riservato <= saldo_totale)
);
