CREATE TABLE prodotti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id BIGINT NOT NULL REFERENCES categorie(id),
    sku VARCHAR(30) NOT NULL UNIQUE,
    nome VARCHAR(200) NOT NULL,
    descrizione TEXT,
    prezzo_fisso NUMERIC(12,2),
    astabile BOOLEAN NOT NULL DEFAULT FALSE,
    quantita_disponibile INT NOT NULL DEFAULT 0,
    quantita_bloccata INT NOT NULL DEFAULT 0,
    attivo BOOLEAN NOT NULL DEFAULT TRUE,
    versione BIGINT NOT NULL DEFAULT 0,
    data_creazione TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (prezzo_fisso IS NULL OR prezzo_fisso > 0),
    CHECK (quantita_disponibile >= 0),
    CHECK (quantita_bloccata >= 0)
);
