CREATE TABLE inventario_utenti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_id BIGINT NOT NULL REFERENCES utenti(id),
    prodotto_id BIGINT NOT NULL REFERENCES prodotti(id),
    quantita INT NOT NULL DEFAULT 0 CHECK (quantita >= 0),
    versione BIGINT NOT NULL DEFAULT 0,
    UNIQUE (utente_id, prodotto_id)
);
