CREATE TABLE aste (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prodotto_id BIGINT NOT NULL REFERENCES prodotti(id),
    admin_id BIGINT NOT NULL REFERENCES utenti(id),
    vincitore_id BIGINT REFERENCES utenti(id),
    stato VARCHAR(20) NOT NULL DEFAULT 'PROGRAMMATA'
        CHECK (stato IN (
            'PROGRAMMATA', 'STANZA_APERTA', 'APERTA', 'CHIUSA', 'ANNULLATA'
        )),
    prezzo_iniziale NUMERIC(12,2) NOT NULL CHECK (prezzo_iniziale > 0),
    incremento_minimo NUMERIC(12,2) NOT NULL DEFAULT 1.00
        CHECK (incremento_minimo > 0),
    offerta_corrente NUMERIC(12,2),
    inizio_at TIMESTAMPTZ NOT NULL,
    fine_at TIMESTAMPTZ NOT NULL,
    chiusa_at TIMESTAMPTZ,
    sequence BIGINT NOT NULL DEFAULT 0,
    versione BIGINT NOT NULL DEFAULT 0,
    data_creazione TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (fine_at >= inizio_at + INTERVAL '7 minutes')
);

CREATE INDEX idx_aste_stato_inizio ON aste(stato, inizio_at);
CREATE INDEX idx_aste_stato_fine ON aste(stato, fine_at);
CREATE INDEX idx_aste_prodotto ON aste(prodotto_id);
CREATE INDEX idx_aste_vincitore ON aste(vincitore_id, chiusa_at DESC);
