CREATE TABLE offerte (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asta_id BIGINT NOT NULL REFERENCES aste(id),
    offerente_id BIGINT NOT NULL REFERENCES utenti(id),
    client_bid_id UUID NOT NULL UNIQUE,
    importo NUMERIC(12,2) NOT NULL CHECK (importo > 0),
    data_offerta TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_offerte_asta_data ON offerte(asta_id, data_offerta DESC);
