CREATE TABLE movimenti_portafoglio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portafoglio_id BIGINT NOT NULL REFERENCES portafogli(id),
    asta_id BIGINT REFERENCES aste(id),
    tipo VARCHAR(30) NOT NULL CHECK (tipo IN (
        'IMPOSTAZIONE_SALDO', 'RISERVA_OFFERTA', 'RILASCIO_OFFERTA',
        'PAGAMENTO_ASTA', 'INCASSO_ASTA', 'ACQUISTO_FISSO'
    )),
    importo NUMERIC(12,2) NOT NULL CHECK (importo > 0),
    saldo_totale_dopo NUMERIC(12,2) NOT NULL,
    saldo_riservato_dopo NUMERIC(12,2) NOT NULL,
    data_movimento TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_movimenti_wallet_data
    ON movimenti_portafoglio(portafoglio_id, data_movimento DESC);
