spring.application.name=product-client
server.port=8082

product-api.base-url=${PRODUCT_API_URL:http://localhost:8081/api/v1}
product-api.connect-timeout=2s
product-api.read-timeout=5s

spring.thymeleaf.cache=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
